[project]
name = "acd.py"
description = "Python module for reading and writing Assetto Corsa Data (.acd) files."
version = "0.0.1"

readme = "README.md"
license = "GPL-2.0"
license-files = ["LICEN[CS]E*"]

classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]

requires-python = ">= 3.8.0"
depencencies = []

[[project.authors]]
name = "Philipp Kosarev"
email = "philipp.kosarev@gmail.com"

[project.urls]
homepage = "https://github.com/philippkosarev/acd.py"
source = "https://github.com/philippkosarev/acd.py"
issues = "https://github.com/philippkosarev/acd.py/issues"
documentation = "https://philippkosarev.github.io/acd.py"

[project.scripts]
acd = "acd.cli:main"

[dependency-groups]
test = ["pytest"]
docs = [
  "sphinx",
  "sphinx-copybutton",
  "pydata-sphinx-theme",
  "commonmark",
]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.hatch.build.targets.wheel]
include = ["acd"]
