# Imports
import os
import io


def get_encryption_key(file, /) -> bytes:
  """Generates an encryption key from a string or path-like object."""
  name = os.path.basename(file).lower()
  if name.startswith('data'):
    file = os.path.abspath(file)
    name = os.path.dirname(file)
    name = os.path.basename(name).lower()
  name = name.encode()
  name_len = len(name)
  # 1
  parts = [sum(name)]
  # 2
  num = 0
  for i in range(0, name_len - 1, 2):
    num = num * name[i] - name[i + 1]
  parts.append(num)
  # 3
  num = 0
  for i in range(1, name_len - 3, 3):
    num *= name[i]
    num = int(num / (name[i + 1] + 27))
    num -= 27 + name[i - 1]
  parts.append(num)
  # 4
  num = 131
  for i in range(1, name_len):
    num -= name[i]
  parts.append(num)
  # 5
  num = 66
  for i in range(1, name_len - 4, 4):
    num = num * (name[i] + 15) * (name[i-1] + 15) + 22
  parts.append(num)
  # 6
  num = 101
  for i in range(0, name_len - 2, 2):
    num -= name[i]
  parts.append(num)
  # 7
  num = 171
  for i in range(0, name_len - 2, 2):
    num = num % name[i]
  parts.append(num)
  # 8
  num = 171
  for i in range(name_len - 1):
    num = int(num / name[i]) + name[i + 1]
  parts.append(num)
  # Assemling and returning
  encryption_key = '-'.join([str(i % 256) for i in parts]).encode()
  return encryption_key


def _decrypt_bytes(data: bytes, encryption_key: bytes) -> bytes:
  encryption_key_len = len(encryption_key)
  num = 0
  buf = bytearray()
  for byte in data[::4]:
    buf.append((byte - encryption_key[num]) % 256)
    num = (num + 1) % encryption_key_len
  return bytes(buf)


def _encrypt_bytes(data: bytes, encryption_key: bytes) -> bytes:
  encryption_key_len = len(encryption_key)
  buf = bytearray()
  num = 0
  for byte in data:
    buf.append((byte + encryption_key[num]) % 256)
    buf.extend(b'\0\0\0')
    num = (num + 1) % encryption_key_len
  return bytes(buf)


def read(fp, encryption_key: bytes) -> dict:
  """Deserialises `fp` (a `.read()`-supporting file-like object) to a
  dictionary where the keys are strings and values are `bytes`.

  The `encryption_key` can be generated by the `get_encryption_key`
  function.
  """
  signature = fp.read(4)
  if signature == b'\xa9\xfb\xff\xff':
    fp.seek(4, 1)
  else:
    fp.seek(-4, 1)
  sections = {}
  while True:
    key_len = fp.read(4)
    if not key_len:
      break
    key_len = int.from_bytes(key_len, byteorder='little')
    key = fp.read(key_len)
    if len(key) != key_len:
      raise EOFError('Unexpected EOF while reading key')
    key = key.decode('utf-8')
    value_len = fp.read(4)
    if not value_len:
      raise EOFError('Unexpected EOF while reading value len')
    value_len = int.from_bytes(value_len, byteorder='little') * 4
    value = fp.read(value_len)
    if len(value) != value_len:
      raise EOFError('Unexpected EOF while reading value')
    sections[key] = _decrypt_bytes(value, encryption_key)
  return sections


def write(data: dict, fp, encryption_key: bytes):
  """Serialises `data` (a dictionary where the keys are strings and
  values are `bytes` or `bytearray`s) to `fp` (a `.write()`-supporting
  file-like object).

  The `encryption_key` can be generated by the `get_encryption_key`
  function.
  """
  # Validating given data
  validated_data = {}
  for key, val in data.items():
    if not isinstance(key, str):
      raise TypeError(f'Key {key!r} in given `data` is not a string')
    key = key.encode('utf-8')
    if not isinstance(val, (bytes, bytearray)):
      raise TypeError(f'Value {val!r} in given `data` is not a string')
    validated_data[key] = val
  # Writing validated data
  for key, value in validated_data.items():
    # Writing key
    key_len = len(key).to_bytes(4, byteorder='little')
    fp.write(key_len)
    fp.write(key)
    # Writing value
    value_len = len(value)
    value_len = value_len.to_bytes(4, byteorder='little')
    fp.write(value_len)
    value = _encrypt_bytes(value, encryption_key)
    fp.write(value)


def read_bytes(data: bytes, encryption_key: bytes) -> dict:
  """Deserialises `data` (a `bytes` or `bytearray` instance) to a
  dictionary where the keys are strings and values are `bytes`.

  The `encryption_key` can be generated by the `get_encryption_key`
  function.
  """
  with io.BytesIO(data) as fp:
    return read(fp, encryption_key)


def write_bytes(data: dict, encryption_key: bytes) -> bytes:
  """Serialises `data` (a dictionary where the keys are strings and
  values are `bytes` or `bytearray`s) to `bytes`.

  The `encryption_key` can be generated by the `get_encryption_key`
  function.
  """
  with io.BytesIO() as fp:
    write(data, fp, encryption_key)
    return fp.getvalue()


def read_file(file) -> dict:
  """Deserialises the contents of the `file` (a `str` or path-like
  object) to a dictionary where the keys are strings and values are
  `bytes`.
  """
  encryption_key = get_encryption_key(file)
  with open(file, 'rb') as fp:
    return read(fp, encryption_key)


def write_file(data: dict, file):
  """Serialises `data` (a dictionary where the keys are strings and
  values are `bytes` or `bytearray`s) and writes the result to the
  `file` (a `str` or path-like object).
  """
  encryption_key = get_encryption_key(file)
  with open(file, 'wb') as fp:
    write(data, fp, encryption_key)
